spring:
  datasource:
    #shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  data:
    jpa:
      repositories:
        enabled: true
        bootstrap-mode: default
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
camunda:
  bpm:
    admin-user:
      id: efimov
      password: pmw3^MU62y4@
      firstName: Алексей
      lastName: Ефимов
    auto-deployment-enabled: true
    deployment-resource-pattern:
      - classpath*:**/*.bpmn
      - classpath*:**/*.bpmn20.xml
      - classpath*:**/*.dmn
      - classpath*:**/*.dmn11.xml
      - classpath*:**/*.form
    #  default-serialization-format: application/json
    filter:
      create: All Tasks
server.port: 8080

